name: CI
on:
  push:
    branches:
      - 'main'
      - 'scratch/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  pull_request:

env:
  BBI_VERSION: v3.3.0

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} R ${{ matrix.config.r }} ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            r: 4.0.5
            # Latest magick requires R 4.1.
            magick_pkg: 'url::https://mpn.metworx.com/snapshots/stable/2025-02-26/src/contrib/magick_2.8.5.tar.gz'
          - os: ubuntu-22.04
            r: 4.3.3
          - os: ubuntu-22.04
            r: 4.4.2
          - os: ubuntu-latest
            r: release
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: metrumresearchgroup/actions/mpn-latest@v1
      - name: Install bbi
        uses: metrumresearchgroup/actions/setup-bbi@v1
        with:
          version: ${{ env.BBI_VERSION }}
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          extra-repositories: 'https://mpn.metworx.com/snapshots/stable/${{ env.MPN_LATEST }}'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::rcmdcheck
            ${{ matrix.config.magick_pkg }}
          upgrade: ${{ matrix.config.r == '4.0.5' && 'FALSE' || 'TRUE' }}
      - uses: r-lib/actions/check-r-package@v2
      - name: Check pkgdown
        shell: Rscript {0}
        run: pkgdown::check_pkgdown()
  release:
    if: github.ref_type == 'tag'
    name: Upload release
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: metrumresearchgroup/actions/mpn-latest@v1
      - name: Install bbi
        uses: metrumresearchgroup/actions/setup-bbi@v1
        with:
          version: ${{ env.BBI_VERSION }}
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          extra-repositories: 'https://mpn.metworx.com/snapshots/stable/${{ env.MPN_LATEST }}'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgpub
            github::tidyverse/glue@v1.7.0
      - uses: metrumresearchgroup/actions/publish-r-release@v1
